// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5vCg_SeKyDkrzyL4v_LNMxmzJ9EaIE9M',
    appId: '1:336224681714:web:0928860e0a885973d79a6b',
    messagingSenderId: '336224681714',
    projectId: 'goodealz-c362e',
    authDomain: 'goodealz-c362e.firebaseapp.com',
    storageBucket: 'goodealz-c362e.firebasestorage.app',
    measurementId: 'G-QNNBJZ83BQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU2BsSFzHT0g--_Xh9223bBXa-_UhpvCA',
    appId: '1:336224681714:android:845d6e7c6c1c8f36d79a6b',
    messagingSenderId: '336224681714',
    projectId: 'goodealz-c362e',
    storageBucket: 'goodealz-c362e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2O_iTipFk4-u13R6RQjugzjod1BqhknA',
    appId: '1:336224681714:ios:b1ba802892708d65d79a6b',
    messagingSenderId: '336224681714',
    projectId: 'goodealz-c362e',
    storageBucket: 'goodealz-c362e.firebasestorage.app',
    iosBundleId: 'com.tqnia.goodealz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2O_iTipFk4-u13R6RQjugzjod1BqhknA',
    appId: '1:336224681714:ios:c03606a6b51a8adfd79a6b',
    messagingSenderId: '336224681714',
    projectId: 'goodealz-c362e',
    storageBucket: 'goodealz-c362e.firebasestorage.app',
    iosBundleId: 'com.example.goodeazapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5vCg_SeKyDkrzyL4v_LNMxmzJ9EaIE9M',
    appId: '1:336224681714:web:a9db6b7ae070048ed79a6b',
    messagingSenderId: '336224681714',
    projectId: 'goodealz-c362e',
    authDomain: 'goodealz-c362e.firebaseapp.com',
    storageBucket: 'goodealz-c362e.firebasestorage.app',
    measurementId: 'G-C28ZBZ60L6',
  );
}
